### ISSUE TITLE
Video Decode Acceleration with NVidia Graphics card modle??

### ISSUE THREAD

**Issue by mmahdi1402** [chinahbcq/ffmpeg_hw_decode#1]
how build this program??
i build ffmpeg opencv and cuda,but while make this program face error libav??
for make program,exist a document?? 
what is your Nvidia Graphics card Modle for run it??
Help me solve this problem.
Thanks for your answers.

**Comment by 6676401088** [comment]
which opencv version you used in this project ?

**Comment by chinahbcq** [comment]
ffmpeg 3.3
cuda 8.0
opencv 2.4.13

makefile and ffmpeg  lib is already in the project.   you should install cuda and opencv.  my gpu card is GeForce GTX 970, and driver is  375.39 .
to build the project, first you should 

**export CMAKE_PREFIX_PATH=/path/to/opencv/dir
export LD_LIBRARY_PATH=$CMAKE_PREFIX_PATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/path/to/ffmpeg/lib:$LD_LIBRARY_PATH**

then 

**make**
