### ISSUE TITLE
avcodec_find_decoder_by_name h264_cuvid failed

### ISSUE THREAD

**Issue by Yang507** [chinahbcq/ffmpeg_hw_decode#2]
hello, i replaced your rtsp_addr in "main.cpp" and run your code, but this is a mistake:
   
     avcodec_find_decoder_by_name h264_cuvid failed

i don't know how to solve the problem, i think i compile ffmpeg maybe lost something. Thanks for your help!

**Comment by chinahbcq** [comment]
make sure you have installed cuda8.0 and libcudnn.so.5.1. 
i have prepared compiled libs in `src ` dir, see below:
```
ffmpeg_hw_decode/src/ffmpeg/lib/
```
please excute `ldd libavcodec.so` , if no dependency lost, you environment is OK.

here provides some tips on how to build ffmpeg on cuda:
```
./configure --prefix=./output \
--enable-shared \
--enable-static \
--enable-nonfree \
--enable-nvenc \
--enable-cuda \
--enable-cuvid 
```
